#!/usr/bin/env python3
"""tests/m6a/gen_fixtures.py — build the M6 fixture container at
tests/m6a/fixtures/model from the M5 fixture model
(tests/m5/fixtures/model), which is ALREADY laid out the way
tools/convert.py lays out the real apus-qwen container (FORMAT_VERSION
2):

  * per-expert 2-member slabs sliced from the fused experts tensors:
    <prefix>.mlp.experts.{E}.gate_up_proj.weight [2I, H] followed by
    .down_proj.weight [H, I], contiguous within one shard;
  * model.safetensors.index.json (weight_map) — copied verbatim;
  * config.json — copied verbatim.

This script adds the piece the M5 fixture does not carry:
apus.index.json with format_version=2 and expert_slabs records
{layer, expert, shard, offset, nbytes} (layer an int — the convert.py
manifest schema), generated by scanning the shard header. It asserts
the v2 slab invariants on the way: every expert has exactly its two
slices, gate_up FIRST, contiguous, uniform slab bytes, [2I,H]/[H,I]
geometry — and that the shard payloads are byte-identical to the M5
shard (this is a copy + manifest, never a requantize).

It also writes tests/m6a/fixtures/model_v1 — a minimal FORMAT_VERSION 1
manifest over an empty weight_map — so test_store can gate the store's
v1 rejection (a v1 3-member container must fail loudly, never be
misread).

Run from the repository root: .venv/bin/python tests/m6a/gen_fixtures.py
(regenerating tests/m5/fixtures first if missing).
"""

import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "tests", "m1"))

import stutil  # noqa: E402

M5_MODEL = os.path.join(ROOT, "tests", "m5", "fixtures", "model")
OUT = os.path.join(HERE, "fixtures")
MODEL = os.path.join(OUT, "model")
MODEL_V1 = os.path.join(OUT, "model_v1")
SHARD = "apus-qwen-00001.safetensors"

EXPERT_RE = re.compile(
    r"^model\.language_model\.layers\.(\d+)\.mlp\.experts\.(\d+)\."
    r"(gate_up_proj|down_proj)\.weight$")
SLAB_MEMBERS = ("gate_up_proj.weight", "down_proj.weight")


def main():
    src_shard = os.path.join(M5_MODEL, SHARD)
    if not os.path.exists(src_shard):
        subprocess.check_call(
            [sys.executable,
             os.path.join(ROOT, "tests", "m5", "gen_fixtures.py")],
            cwd=ROOT)
    os.makedirs(MODEL, exist_ok=True)

    # copy the container files verbatim (shard, standard index, config)
    for f in (SHARD, "model.safetensors.index.json", "config.json"):
        shutil.copyfile(os.path.join(M5_MODEL, f), os.path.join(MODEL, f))

    hdr, data_start = stutil.read_shard(os.path.join(MODEL, SHARD))
    raw = stutil.read_tensor_bytes(os.path.join(MODEL, SHARD), hdr,
                                   data_start)
    hdr5, ds5 = stutil.read_shard(src_shard)
    raw5 = stutil.read_tensor_bytes(src_shard, hdr5, ds5)

    # group expert slices; assert the v2 slab invariants
    slabs = {}
    for name in hdr:
        m = EXPERT_RE.match(name)
        if m:
            key = (int(m.group(1)), int(m.group(2)))
            slabs.setdefault(key, {})[f"{m.group(3)}.weight"] = name
    assert slabs, "no v2 expert slab slices found"
    slab_records = []
    slab_bytes = None
    for key in sorted(slabs):
        layer, eid = key
        members = slabs[key]
        missing = [s for s in SLAB_MEMBERS if s not in members]
        assert not missing, f"expert {key}: missing {missing}"
        assert len(members) == 2, f"expert {key}: extra members"
        offs = []
        for suffix in SLAB_MEMBERS:
            name = members[suffix]
            a, b = hdr[name]["data_offsets"]
            offs.append((data_start + a, data_start + b,
                         hdr[name]["shape"]))
        # gate_up FIRST, contiguous, [2I, H] + [H, I] geometry
        assert offs[0][1] == offs[1][0], \
            f"expert {key}: gate_up/down not contiguous/in order"
        gu_sh, d_sh = offs[0][2], offs[1][2]
        assert len(gu_sh) == 2 and len(d_sh) == 2
        assert gu_sh[0] == 2 * d_sh[1] and gu_sh[1] == d_sh[0], \
            f"expert {key}: bad geometry {gu_sh} vs {d_sh}"
        nb = offs[1][1] - offs[0][0]
        if slab_bytes is None:
            slab_bytes = nb
        assert nb == slab_bytes, f"expert {key}: non-uniform slab bytes"
        slab_records.append({
            "layer": layer,
            "expert": eid,
            "shard": SHARD,
            "offset": offs[0][0],
            "nbytes": nb,
        })

    # manifest (the convert.py v2 schema, minus fields the store does
    # not consume; header_reserve n/a for the fixture's plain shard)
    tensor_map = {}
    for name, meta in hdr.items():
        a, b = meta["data_offsets"]
        tensor_map[name] = {
            "shard": SHARD,
            "offset": data_start + a,
            "nbytes": b - a,
            "dtype": meta["dtype"],
            "shape": meta["shape"],
        }
    manifest = {
        "format_version": 2,
        "config_hash": "m6a-fixture",
        "offset_base": "file",
        "header_reserve": None,
        "shard_groups": {"main": [SHARD]},
        "ntensors": len(tensor_map),
        "tensor_map": tensor_map,
        "expert_slabs": slab_records,
        "stripped_tensors": 0,
    }
    with open(os.path.join(MODEL, "apus.index.json"), "w") as f:
        json.dump(manifest, f, indent=1)

    # byte-identity audit: every payload equal to the M5 shard's
    for name in hdr5:
        assert raw[name] == raw5[name], f"{name}: payload changed"

    # the v1 negative fixture: a FORMAT_VERSION 1 manifest (the Ling
    # 3-member-slab era) over an empty weight_map — the store must
    # reject it loudly.
    os.makedirs(MODEL_V1, exist_ok=True)
    with open(os.path.join(MODEL_V1, "model.safetensors.index.json"),
              "w") as f:
        json.dump({"metadata": {}, "weight_map": {}}, f)
    with open(os.path.join(MODEL_V1, "apus.index.json"), "w") as f:
        json.dump({"format_version": 1, "expert_slabs": []}, f)

    n_layers = 1 + max(r["layer"] for r in slab_records)
    n_experts = 1 + max(r["expert"] for r in slab_records)
    print(f"m6a fixture: {len(hdr)} tensors, {len(slab_records)} expert "
          f"slabs ({n_layers} layers x {n_experts} experts, all MoE), "
          f"slab {slab_bytes} B (2-member v2), contiguity + geometry "
          f"verified, payloads byte-identical; v1 negative fixture "
          f"written")


if __name__ == "__main__":
    main()
