#!/usr/bin/env python3
"""tests/m5/gen_fixtures.py — generate the M5 full-mini-model fixtures:
the apus-qwen container (safetensors shard + model.safetensors.index.json
+ config.json, REAL qwen3_5_moe schema and M1 container naming) plus
golden sequences from the oracle (tools/oracle.py). Deterministic (seeds
documented).

Container conventions (the M1 output schema, tools/convert.py):
  - dense tensors under their HF names (model.language_model.*,
    lm_head.weight);
  - the fused expert tensors are SLICED per expert into the synthesized
    2-member slab names
    <prefix>.mlp.experts.{E}.{gate_up_proj,down_proj}.weight, written
    gate_up-then-down contiguously per expert (the real slab layout);
  - config.json carries the nested text_config schema
    (reference/config.json in miniature) including decorative real keys
    the loader must ignore, and mtp_num_hidden_layers=1 with NO mtp
    tensors (the loader must tolerate the mtp shard group's absence).

Mini model: oracle.MINI_CFG (hidden 128, 2 layers [linear_attention,
full_attention] — one of each kind, 16 experts top-4, vocab 256), the
tests/m0 fixture config.

Golden sequences (f32 = C target, f64 = truth):
  prefill6 / prefill64     per-position logits [T, 256]
  dec32                    prefill 32 + 8 decode steps, fixed ids,
                           per-step logits
  greedy                   16-step greedy continuation of a 24-token
                           context: tokens, teacher-forced logits,
                           top1-top2 gap per step
  sampled                  16-step continuation at temp 0.6 / top_k 20 /
                           top_p 0.95: tokens, teacher-forced logits,
                           consumed PCG64 uniforms (seed 20260805), CDF
                           margin per step
  trace                    h after each layer on the greedy chain context
                           (both modes) -> envelope.txt
  cli_greedy.txt           the 8 greedy tokens the Makefile CLI smoke
                           diffs against (ids "3,1,4,1,5,9,2,6")

Chains are generated by iterative one-shot prefills (Apus M5 lesson).
The golden path consumes ONLY weights read back from the container (the
Apus M4c lesson: independent realization).

Run from the repository root: .venv/bin/python tests/m5/gen_fixtures.py
"""

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "tests", "m1"))

import oracle  # noqa: E402
import stutil  # noqa: E402

FIX = os.path.join(HERE, "fixtures")
MODEL = os.path.join(FIX, "model")
SHARD = "apus-qwen-00001.safetensors"
CFG = oracle.MINI_CFG

SEED = 20260831          # the m0 seed: clean router top-k margins
SAMPLE_RNG_SEED = 20260805

GREEDY_STEPS = 16
SAMPLED_STEPS = 16
SAMPLE_TEMP = 0.6
SAMPLE_TOP_K = 20
SAMPLE_TOP_P = 0.95

CLI_IDS = [3, 1, 4, 1, 5, 9, 2, 6]
CLI_TOKENS = 8


def dump(name, arr):
    np.asarray(arr).tofile(os.path.join(FIX, name))


# --------------------------------------------------------------------------
# sampling helpers (c/sample.h contract; ported verbatim from the Ling
# base oracle — model-agnostic): argmax lowest index on ties; fp32
# max-subtracted softmax; top-k FIRST (stable), then top-p nucleus (HF
# shift rule), renormalized CDF draw = smallest j with CDF[j] > u.

def probs_from_logits(logits, temp):
    """FP32 max-subtracted softmax of logits/temp (c/sample.h)."""
    z = (np.asarray(logits, dtype=np.float64) / temp).astype(np.float32)
    z = z - z.max()
    with np.errstate(over="ignore"):
        e = np.exp(z)
    return (e / e.sum()).astype(np.float32)


def top_kp_draw(probs, top_k, top_p, u):
    """Top-k truncation then top-p nucleus (HF shift rule), stable desc
    sort (lowest index on exact ties), renormalized CDF draw: smallest j
    with CDF[j] > u (== c/sample.h apus_sample_top_kp_u). Returns
    (token, margin) where margin = min distance from u to the drawn
    entry's CDF edges."""
    order = np.argsort(-probs, kind="stable")
    if 0 < top_k < len(probs):
        order = order[:top_k]
    kept = []
    cum = 0.0
    for i in order:
        if cum <= top_p:
            cum += float(probs[i])
            kept.append(i)
        else:
            break
    if not kept:
        kept = [order[0]]
        cum = float(probs[order[0]])
    c = 0.0
    for i in kept:
        lo = c
        c += float(probs[i]) / cum
        if u < c:
            return int(i), min(u - lo, c - u)
    return int(kept[-1]), min(u - (c - float(probs[kept[-1]]) / cum), 0.0)


def top2_gap(logits):
    s = np.sort(np.asarray(logits, dtype=np.float64))
    return float(s[-1] - s[-2])


# --------------------------------------------------------------------------
# container write/read (M1 output schema)

def _slicewise_experts(named, L, E):
    """Per-expert slab slice entries for layer L (2-member slabs,
    gate_up then down, contiguous per expert — the converter layout)."""
    p = f"model.language_model.layers.{L}.mlp.experts"
    gu = named[p + ".gate_up_proj"]        # [E, 2I, H] bf16 codes
    d = named[p + ".down_proj"]            # [E, H, I] bf16 codes
    out = []
    for e in range(E):
        out.append((f"{p}.{e}.gate_up_proj.weight", gu[e]))
        out.append((f"{p}.{e}.down_proj.weight", d[e]))
    return out


def write_container(named):
    os.makedirs(MODEL, exist_ok=True)
    E = CFG["num_experts"]
    n_layers = CFG["num_hidden_layers"]
    expert_src = set()
    for L in range(n_layers):
        p = f"model.language_model.layers.{L}.mlp.experts"
        expert_src.add(p + ".gate_up_proj")
        expert_src.add(p + ".down_proj")
    entries = []
    # globals first (the real layout: embed/norm/lm_head in shard 1)
    for name in sorted(named):
        if name in expert_src or name.startswith(
                "model.language_model.layers."):
            continue
        entries.append((name, named[name]))
    # per layer: dense tensors (sorted), then the per-expert slabs
    for L in range(n_layers):
        pre = f"model.language_model.layers.{L}."
        for name in sorted(n for n in named
                           if n.startswith(pre) and n not in expert_src):
            entries.append((name, named[name]))
        entries.extend(_slicewise_experts(named, L, E))

    tensors = []
    weight_map = {}
    for name, arr in entries:
        if arr.dtype == np.uint16:
            dtype = "BF16"
        elif arr.dtype == np.float32:
            dtype = "F32"
        else:
            raise ValueError(f"{name}: dtype {arr.dtype}")
        tensors.append((name, dtype, list(arr.shape), arr.tobytes()))
        weight_map[name] = SHARD
    stutil.write_shard(os.path.join(MODEL, SHARD), tensors)
    with open(os.path.join(MODEL, "model.safetensors.index.json"),
              "w") as f:
        json.dump({"metadata": {}, "weight_map": weight_map}, f)

    # nested text_config schema (reference/config.json in miniature),
    # incl. decorative keys the loader must ignore and an mtp block on
    # paper only (NO mtp tensors — absence must be tolerated)
    text_cfg = {k: v for k, v in CFG.items()
                if k not in ("prefill_len", "decode_len")}
    text_cfg.update({
        "attn_output_gate": True,           # decorative (contract §4)
        "mamba_ssm_dtype": "float32",       # decorative
        "router_aux_loss_coef": 0.001,      # training-only
        "output_router_logits": False,
        "full_attention_interval": 4,
        "mtp_num_hidden_layers": 1,         # mtp shard group ABSENT
        "mtp_use_dedicated_embeddings": False,
        "eos_token_id": 248044,             # outside the mini vocab
        "bos_token_id": 248044,
        "tie_word_embeddings": False,
        "use_cache": True,
    })
    config = {
        "architectures": ["Qwen3_5MoeForConditionalGeneration"],
        "model_type": "qwen3_5_moe",
        "dtype": "bfloat16",
        "text_config": text_cfg,
        "vision_config": {"model_type": "qwen3_5_moe", "hidden_size": 48},
        "tie_word_embeddings": False,
    }
    with open(os.path.join(MODEL, "config.json"), "w") as f:
        json.dump(config, f, indent=1)


def load_container():
    """Read the container back (the golden path consumes ONLY this).
    Per-expert slab slices are restacked into the fused oracle names —
    from DISK bytes, never the generation arrays."""
    hdr, data_start = stutil.read_shard(os.path.join(MODEL, SHARD))
    raw = stutil.read_tensor_bytes(os.path.join(MODEL, SHARD), hdr,
                                   data_start)
    named = {}
    E = CFG["num_experts"]
    gu = {}
    d = {}
    for name, meta in hdr.items():
        b = raw[name]
        if meta["dtype"] == "BF16":
            arr = np.frombuffer(b, dtype=np.uint16).reshape(meta["shape"])
            val = oracle.bf16_widen_f64(arr)
        elif meta["dtype"] == "F32":
            val = np.frombuffer(b, dtype=np.float32).reshape(
                meta["shape"]).astype(np.float64)
        else:
            raise ValueError(meta["dtype"])
        if ".mlp.experts." in name and name.endswith(
                ".gate_up_proj.weight"):
            pre, e = name.split(".gate_up_proj.weight")[0], None
            e = int(pre.rsplit(".", 1)[1])
            gu[(pre.rsplit(".mlp.experts.", 1)[0], e)] = val
        elif ".mlp.experts." in name and name.endswith(
                ".down_proj.weight"):
            pre = name.split(".down_proj.weight")[0]
            e = int(pre.rsplit(".", 1)[1])
            d[(pre.rsplit(".mlp.experts.", 1)[0], e)] = val
        else:
            named[name] = val
    for (pre, e), val in sorted(gu.items()):
        key = pre + ".mlp.experts.gate_up_proj"
        named.setdefault(key, [None] * E)[e] = val
    for (pre, e), val in sorted(d.items()):
        key = pre + ".mlp.experts.down_proj"
        named.setdefault(key, [None] * E)[e] = val
    for key in [k for k, v in named.items() if isinstance(v, list)]:
        named[key] = np.stack(named[key], axis=0)
    return named


def gen_sequence_ids(rng):
    V = CFG["vocab_size"]
    ids = {}
    ids["prefill6"] = rng.integers(0, V, 6)
    ids["prefill64"] = rng.integers(0, V, 64)
    ids["dec32"] = rng.integers(0, V, 32 + 8)
    ids["greedy_ctx"] = rng.integers(0, V, 24)
    ids["sampled_ctx"] = rng.integers(0, V, 24)
    return ids


def main():
    os.makedirs(FIX, exist_ok=True)
    rng = np.random.default_rng(SEED)
    named_codes, _ = oracle.gen_full_weights(rng, CFG)
    write_container(named_codes)
    named = load_container()          # f64 values, from DISK

    ids = gen_sequence_ids(np.random.default_rng(SEED + 1))
    for k, v in ids.items():
        dump(f"ids_{k}.bin", v.astype(np.int64))

    # --- prefill goldens ---------------------------------------------------
    for key in ("prefill6", "prefill64"):
        for mode in ("f32", "f64"):
            logits, _ = oracle.full_forward(named, ids[key], mode, CFG)
            dump(f"{key}_logits_{mode}.bin", logits)

    # --- dec32 ---------------------------------------------------------------
    d = ids["dec32"]
    for mode in ("f32", "f64"):
        states = [oracle.new_state(oracle.layer_kind(CFG, L), CFG)
                  for L in range(CFG["num_hidden_layers"])]
        oracle.full_forward(named, d[:32], mode, CFG, states=states)
        for i in range(8):
            logits, _ = oracle.full_forward(named, d[32 + i:33 + i], mode,
                                            CFG, states=states)
            dump(f"dec32_step{i}_logits_{mode}.bin", logits)

    # --- greedy chain (one-shot prefills, f32 = C target) -------------------
    ctx = list(ids["greedy_ctx"])
    steps_g = []
    chain = list(ctx)
    for s in range(GREEDY_STEPS):
        logits32, _ = oracle.full_forward(named, chain, "f32", CFG)
        logits64, _ = oracle.full_forward(named, chain, "f64", CFG)
        last32, last64 = logits32[-1], logits64[-1]
        nxt = int(np.argmax(last32))
        steps_g.append(dict(token=nxt, l32=last32, l64=last64,
                            gap=top2_gap(last32)))
        chain.append(nxt)
    dump("greedy_tokens.bin", np.array([s["token"] for s in steps_g],
                                       dtype=np.int64))
    dump("greedy_gap.bin", np.array([s["gap"] for s in steps_g]))
    for s, stp in enumerate(steps_g):
        dump(f"greedy_step{s}_logits_f32.bin", stp["l32"])
        dump(f"greedy_step{s}_logits_f64.bin", stp["l64"])

    # --- sampled chain ------------------------------------------------------
    srng = np.random.default_rng(SAMPLE_RNG_SEED)   # PCG64
    ctx = list(ids["sampled_ctx"])
    steps_s = []
    chain = list(ctx)
    for s in range(SAMPLED_STEPS):
        logits32, _ = oracle.full_forward(named, chain, "f32", CFG)
        logits64, _ = oracle.full_forward(named, chain, "f64", CFG)
        last32, last64 = logits32[-1], logits64[-1]
        probs = probs_from_logits(last32, SAMPLE_TEMP)
        u = float(srng.random())
        tok, margin = top_kp_draw(probs, SAMPLE_TOP_K, SAMPLE_TOP_P, u)
        steps_s.append(dict(token=tok, l32=last32, l64=last64, u=u,
                            margin=margin))
        chain.append(tok)
    dump("sampled_tokens.bin", np.array([s["token"] for s in steps_s],
                                        dtype=np.int64))
    dump("sampled_u.bin", np.array([s["u"] for s in steps_s]))
    dump("sampled_margin.bin", np.array([s["margin"] for s in steps_s]))
    for s, stp in enumerate(steps_s):
        dump(f"sampled_step{s}_logits_f32.bin", stp["l32"])
        dump(f"sampled_step{s}_logits_f64.bin", stp["l64"])

    # --- per-layer hidden traces on the greedy chain context ----------------
    gchain = list(ids["greedy_ctx"]) + [s["token"] for s in steps_g]
    env_rows = []
    for mode in ("f32", "f64"):
        logits, traces = oracle.full_forward(named, gchain, mode, CFG)
        for L, h in enumerate(traces):
            dump(f"trace_L{L}_{mode}.bin", h)
        dump(f"trace_logits_{mode}.bin", logits)
    for L in range(CFG["num_hidden_layers"]):
        a = np.fromfile(os.path.join(FIX, f"trace_L{L}_f32.bin"))
        b = np.fromfile(os.path.join(FIX, f"trace_L{L}_f64.bin"))
        m = float(np.abs(a - b).max())
        rel = m / float(np.abs(b).max())
        env_rows.append((f"h_after_L{L}", m, rel))
    a = np.fromfile(os.path.join(FIX, "trace_logits_f32.bin"))
    b = np.fromfile(os.path.join(FIX, "trace_logits_f64.bin"))
    m = float(np.abs(a - b).max())
    rel = m / float(np.abs(b).max())
    V = CFG["vocab_size"]
    flips = int(np.count_nonzero(
        np.argmax(a.reshape(-1, V), axis=1)
        != np.argmax(b.reshape(-1, V), axis=1)))
    env_rows.append(("logits", m, rel))
    with open(os.path.join(FIX, "envelope.txt"), "w") as f:
        for name, mm, rl in env_rows:
            f.write(f"{name} {mm:.9g} {rl:.9g}\n")
            print(f"envelope {name:14s} maxabs {mm:.4g} rel {rl:.4g}")
    print(f"envelope argmax flips (trace): {flips}/{len(gchain)}")

    # --- CLI smoke golden -----------------------------------------------------
    chain = list(CLI_IDS)
    toks = []
    for _ in range(CLI_TOKENS):
        logits, _ = oracle.full_forward(named, chain, "f32", CFG)
        nxt = int(np.argmax(logits[-1]))
        toks.append(nxt)
        chain.append(nxt)
    with open(os.path.join(FIX, "cli_greedy.txt"), "w") as f:
        for t in toks:
            f.write(f"{t}\n")
    print("cli greedy:", " ".join(str(t) for t in toks))

    with open(os.path.join(FIX, "manifest.txt"), "w") as f:
        f.write(f"seed={SEED}\nsample_seed={SAMPLE_RNG_SEED}\n")
        f.write(f"greedy_steps={GREEDY_STEPS}\n")
        f.write(f"sampled_steps={SAMPLED_STEPS}\n")
        f.write("decode_steps=8\n")
    print("fixtures written:", FIX)


if __name__ == "__main__":
    main()
