#!/usr/bin/env python3
"""Generate c/uni_tables.h: Unicode class range tables for the apus tokenizer.

The classes are DERIVED FROM THE TOKENIZER'S OWN PRE-TOKENIZER BEHAVIOR
(reference/tokenizer.json via the HF `tokenizers` lib), not from unicodedata,
so they exactly match whatever Unicode version the Rust regex crate uses.

The Qwen2 pre-tokenizer is a single Split(regex, Isolated) stage with the
GPT-2-style pattern (byte-level pieces shown after ByteLevel):

  '(?i:'s|'t|'re|'ve|'m|'ll|'d)     contraction
  | [^\r\n\p{L}\p{N}]?[\p{L}\p{M}]+ opt non-L/N prefix + letter/mark run
  | \p{N}                           single digit (numbers split per char!)
  |  ?[^\s\p{L}\p{M}\p{N}]+[\r\n]*  opt space + punct/symbol run + newlines
  | \s*[\r\n]+                      whitespace ending in newline(s)
  | \s+(?!\S)                       trailing whitespace
  | \s+                             other whitespace

Classes the matcher needs per codepoint:
  N     -> \p{N}
  L     -> \p{L}\p{M} (marks JOIN the letter class in this pattern: the
           letter-run body is [\p{L}\p{M}]+ and the punct class excludes
           \p{M}; the emitted uni_l_ranges therefore cover L and M)
  WS    -> regex \s (White_Space)
  OTHER -> everything else (category C, punctuation, symbols; matched by
           the [^\s\p{L}\p{M}\p{N}] punct/symbol class)

Probes per codepoint cp (>= 0x80, non-surrogate; ASCII is hardcoded in tok.h):
  "x"+cp+"x"  -> 3 pieces iff N   (letters "x" isolate; \p{N} matches single
                                   chars; every other class merges with an
                                   adjacent "x" via the prefix+letters or
                                   punct-run alternatives)
  "x"+cp      -> 1 piece  iff L|M (letter/mark run swallows both)
  "!!"+cp+"!!"-> 3 pieces iff WS  (punct runs cannot cross \s; 1 piece for
                                   OTHER, whose run swallows the whole string)
"""

import sys
from tokenizers import Tokenizer

ROOT = sys.argv[1] if len(sys.argv) > 1 else "."
TOK_PATH = ROOT + "/reference/tokenizer.json"
OUT_PATH = ROOT + "/c/uni_tables.h"

CLS_OTHER, CLS_N, CLS_L, CLS_WS = 0, 1, 2, 3
NAMES = {CLS_N: "N", CLS_L: "L", CLS_WS: "WS"}


def main():
    tok = Tokenizer.from_file(TOK_PATH)
    pt = tok.pre_tokenizer

    def pieces(s):
        return [p for p, _ in pt.pre_tokenize_str(s)]

    cls = {}
    cps = [cp for cp in range(0x80, 0x110000) if not (0xD800 <= cp <= 0xDFFF)]
    for i, cp in enumerate(cps):
        c = chr(cp)
        p1 = pieces("x" + c + "x")
        if len(p1) == 3 and p1[0] == "x" and p1[2] == "x":
            cls[cp] = CLS_N
            continue
        p2 = pieces("x" + c)
        if len(p2) == 1:
            cls[cp] = CLS_L
            continue
        p3 = pieces("!!" + c + "!!")
        if len(p3) == 3 and p3[0] == "!!" and p3[2] == "!!":
            cls[cp] = CLS_WS
        else:
            cls[cp] = CLS_OTHER
        if (i + 1) % 100000 == 0:
            print(f"\r{i + 1}/{len(cps)}", end="", flush=True)
    print()

    # build ranges per class (sorted by cp; surrogates stay unassigned -> OTHER)
    out = {CLS_N: [], CLS_L: [], CLS_WS: []}
    sorted_cps = sorted(cls)
    for target in (CLS_N, CLS_L, CLS_WS):
        start = None
        prev = None
        for cp in sorted_cps:
            if cls[cp] == target:
                if start is None:
                    start = cp
                prev = cp
            else:
                if start is not None:
                    out[target].append((start, prev))
                    start = None
        if start is not None:
            out[target].append((start, prev))

    with open(OUT_PATH, "w") as f:
        f.write("/* Generated by tests/m2/gen_uni_tables.py — do not edit.\n")
        f.write("   Unicode class ranges derived from the reference tokenizer's own\n")
        f.write("   pre-tokenizer behavior (reference/tokenizer.json). The L\n")
        f.write("   ranges cover \\p{L}\\p{M} (marks join the letter class in the\n")
        f.write("   Qwen2 pre-tokenizer pattern). */\n")
        f.write("#ifndef APUS_UNI_TABLES_H\n#define APUS_UNI_TABLES_H\n\n")
        f.write("#include <stdint.h>\n\n")
        for target in (CLS_N, CLS_L, CLS_WS):
            name = NAMES[target]
            rng = out[target]
            f.write(f"static const uint32_t uni_{name.lower()}_ranges[][2] = {{\n")
            for lo, hi in rng:
                f.write(f"    {{0x{lo:06X}u, 0x{hi:06X}u}},\n")
            f.write("};\n")
            f.write(f"#define UNI_{name}_NRANGES {len(rng)}u\n\n")
        f.write("#endif\n")

    for target in (CLS_N, CLS_L, CLS_WS):
        rng = out[target]
        total = sum(hi - lo + 1 for lo, hi in rng)
        print(f"{NAMES[target]}: {len(rng)} ranges, {total} codepoints")
    print("wrote", OUT_PATH)


if __name__ == "__main__":
    main()
